"""adiciona a coluna CPF e saldo a tabela 'users'

Revision ID: 99e9ce9c1ad7
Revises: 0b991d2bb18b
Create Date: 2026-07-31 22:46:36.254810

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99e9ce9c1ad7"
down_revision: Union[str, Sequence[str], None] = "0b991d2bb18b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("cpf", sa.String(length=20), nullable=False))
    op.add_column(
        "users", sa.Column("saldo", sa.Numeric(precision=10, scale=2), nullable=False)
    )
    op.create_unique_constraint(None, "users", ["cpf"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "saldo")
    op.drop_column("users", "cpf")
    # ### end Alembic commands ###
